### ISSUE TITLE
Error with loading roster files

### ISSUE THREAD

**Issue by minqii** [tillhanke/QuidditchScoreboard#10]
This error appears when loading roster files: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1699, in __call__
  File "Main.py", line 263, in <lambda>
  File "Main.py", line 115, in set
  File "c:\users\tillv\dropbox\hiwi\progra~1\simpso~1\venv\lib\codecs.py", line 321, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 1: invalid start byte

This happened with the Düsseldorf file (along with all the other NRW teams) but not with the Bielefeld file. Couldnt spot the difference between them 

[Düsseldorf Dementors.txt](https://github.com/tillhanke/QuidditchScoreboard/files/2248665/Dusseldorf.Dementors.txt)
[Bielefelder Basilisken.txt](https://github.com/tillhanke/QuidditchScoreboard/files/2248666/Bielefelder.Basilisken.txt)

**Comment by tillhanke** [comment]
Thats an issue with the UTF-8 decoding that the scoreboard assumes. It can't handle the German umlaute üäö so it throws the error. The fix should be quite straight forward 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
